export const DASHBOARD_PATH = '/dashboard'
export const DASHBOARD_EDIT_PATH = '/dashboard/edit'
export const CALENDAR_PATH = '/calendar'
export const NOTE_PATH = '/note'
export const PLANNER_PATH = '/planner'
export const STORE_PATH = '/store'
export const LOGIN_PATH = '/login'
export const SIGNUP_PATH = '/signup'
