import { Common } from './common'

export const themeDefault = {
  background: Common.colors.white02,
  panel: Common.colors.white,
  border: Common.colors.blue01,
  text: Common.colors.black02,
  subText: Common.colors.gray03,
  button: Common.colors.blue02,
  buttonText: Common.colors.white,
  errorRed: Common.colors.red01,
  successBlue: Common.colors.blue03,
  infoGreen: Common.colors.green01,
  warningYellow: Common.colors.yellow01,
  inputBackground: Common.colors.white,
  inputText: Common.colors.black02,
  inputLabel: Common.colors.black,
  hoverText: Common.colors.blue02,
  menuButton: Common.colors.gray02,
  menuText: Common.colors.gray03,
  menuBackground: Common.colors.white,
  menuHover: Common.colors.gray03,
  navBackground: Common.colors.white,
  navActiveBackground: Common.colors.gray04,
  navActiveText: Common.colors.black02,
  navText: Common.colors.gray03,
  icon: Common.colors.gray02,
  iconActive: Common.colors.blue02,
  clockText: Common.colors.blue02,
  dateText: Common.colors.gray03,
  alertBackground: Common.colors.white,
  alertTitle: Common.colors.gray03,
  alertText: Common.colors.black02,
  alertButtonBackground: Common.colors.white,
  alertButtonBoard: Common.colors.gray03,
  alertOkButton: Common.colors.blue02,
  alertOkButtonText: Common.colors.white,
  selectBorder: Common.colors.blue02,
  selectBackground: Common.colors.white02,
  selectText: Common.colors.blue02,
  selectOptionBackground: Common.colors.white,
}
