import { Common } from './common'

export const themeDefault = {
  background: Common.colors.blue01,
  subBackground: Common.colors.gray01,
  mainBackground: Common.colors.blue02,
  lightBackground: Common.colors.white,
  panel: Common.colors.white,
  border: Common.colors.blue01,
  text: Common.colors.black02,
  subText: Common.colors.gray03,
  mainText: Common.colors.blue02,
  button: Common.colors.blue02,
  buttonText: Common.colors.white,
  subButton: Common.colors.gray02,
  subButtonText: Common.colors.gray03,
  borderButtonborder: Common.colors.blue02,
  borderButtonText: Common.colors.blue02,
  borderButtonGray: Common.colors.gray03,
  borderButtonGrayText: Common.colors.gray03,
  lightButton: Common.colors.white,
  //alert color
  errorRed: Common.colors.red01,
  successBlue: Common.colors.blue03,
  infoGreen: Common.colors.green01,
  warningYellow: Common.colors.yellow01,
  //input
  inputBackground: Common.colors.white,
  inputText: Common.colors.black02,
  inputLabel: Common.colors.black,
  //toggle&header menu
  hoverText: Common.colors.blue02,
  menuButton: Common.colors.gray02,
  menuText: Common.colors.gray03,
  menuBackground: Common.colors.white,
  menuHover: Common.colors.gray03,
  //nav
  navBackground: Common.colors.white,
  navActiveBackground: Common.colors.gray04,
  navActiveText: Common.colors.black02,
  navText: Common.colors.gray03,
  icon: Common.colors.gray02,
  iconActive: Common.colors.blue02,
  //widget-clock
  clockText: Common.colors.blue02,
  dateText: Common.colors.gray03,
  //alert
  alertBackground: Common.colors.white,
  alertTitle: Common.colors.gray03,
  alertText: Common.colors.black02,
  alertButtonBackground: Common.colors.white,
  alertButtonBoard: Common.colors.gray03,
  alertOkButton: Common.colors.blue02,
  alertOkButtonText: Common.colors.white,
  //select
  selectBorder: Common.colors.blue02,
  selectBackground: Common.colors.blue01,
  selectText: Common.colors.blue02,
  selectOptionBackground: Common.colors.white,
  //subSelect
  subSelectBorder: Common.colors.blue02,
  subSelectBackground: Common.colors.white,
  subSelectText: Common.colors.gray03,
  subSelectOptionBackground: Common.colors.white,
  //header
  headerBackground: Common.colors.white,
  headerText: Common.colors.black02,
  headerButtons: Common.colors.blue02,
  subHeaderBackground: Common.colors.blue02,
  subHeaderText: Common.colors.white,
  //dashboard edit
  widgetSettingButtons: Common.colors.gray03,
  widgetListBackground: Common.colors.gray05,
  widgetListTitleText: Common.colors.blue02,
  previewBackground: Common.colors.white,
  previewText: Common.colors.gray03,
  previewPointText: Common.colors.blue02,
  previewSubText: Common.colors.gray02,
  previewSubText2: Common.colors.gray05,
  previewPanelBackground: Common.colors.blue01,
  previewPanelBorder: Common.colors.gray02,
  previewPanelDeleteButton: Common.colors.gray03,
  previewPanelDeleteButtonhover: Common.colors.blue02,
  previewSaveActiveButtonBackground: Common.colors.blue02,
  previewSaveActiveButtonText: Common.colors.white,
  previewSaveButtonBackground: Common.colors.gray03,
  previewSaveButtonText: Common.colors.white,
  //scrollbar
  scrollbarThumb: Common.colors.gray03,
  scrollbarTrack: Common.colors.gray02,
  scrollbarTrackBorder: Common.colors.gray02,
  //modal
  modalBackground: Common.colors.black,
  modalContainerBackground: Common.colors.white,
  modalSubText: Common.colors.gray03,
  //toggleButton
  toggleButtonBackground: Common.colors.blue01,
  toggleButtonActive: Common.colors.blue02,
  toggleButton: Common.colors.gray03,
  //react-grid-DragDropOver
  dragDropOverBackground: Common.colors.blue02,
  //checkbox
  checkboxBackground: Common.colors.gray02,
  checkboxActiveBackground: Common.colors.blue02,
  checkboxText: Common.colors.gray05,
  checkboxActiveText: Common.colors.white,
  checkboxActiveSubText: Common.colors.blue03,
  checkLabelText: Common.colors.black02,
  checkLabelSubText: Common.colors.gray03,
  //etc
  agreeMoreButtonColor: Common.colors.gray03,
}
